# Aviary is an audiovisual content publishing platform with sophisticated features for search and permissions controls.
# Copyright (C) 2019 Audio Visual Preservation Solutions, Inc.
version: '3.0'
services:
  db:
    image: mysql:5.7
    env_file: .env
    environment:
      MYSQL_DATABASE: 'aviarypublic'
      MYSQL_ROOT_PASSWORD: 'password1234!&*'
    volumes:
      - db-data:/var/lib/mysql
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  solr:
    image: solr:9.0.0
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/mycores
      - ./solr:/solr-config
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - aviarypublic
      - /solr-config/configsets/sunspot/conf
    depends_on:
      - db

  app: &app_base
    build: .
    env_file: .env
    command: bash -c "./bin/docker/prepare-to-start-rails && ./bin/rails server -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: 'development'
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - solr
    volumes:
      - .:/aviary

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom nginx.conf file
    depends_on:
      - app
  
  worker:
    <<: *app_base
    command: bundle exec sidekiq
    volumes:
      - cron-data:/var/spool/cron/crontabs
    ports: []
    depends_on:
      - app
      - db
      - redis

volumes:
  db-data:
  solr-data:
  cron-data:
  redis-data:
