development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: aviary

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['ACTION_CABLE_REDIS'] %>
  channel_prefix: aviary
