default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PWD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 3306
  variables:
    sql_mode: TRADITIONAL

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PWD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 3306
  variables:
    sql_mode: TRADITIONAL
