production:
  solr:
    hostname: <%= ENV['SOLR_HOST'] || "localhost" %>
    port: 8983
    log_level: WARNING
    path: /solr/production

development:
  solr:
    hostname: <%= ENV['SOLR_HOST'] || "localhost" %>
    port: 8983
    log_level: INFO
    path: /solr/development
    
test:
  solr:
    hostname: <%= ENV['SOLR_HOST'] || "localhost" %>
    port: 8983
    log_level: WARNING
    path: /solr/test
    