name: Update License Information
on: 
  pull_request:
    branches:
      - dev
      - main

jobs:
  verify_conditions: 
    name: Verify Conditions
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    outputs:
      status: ${{ steps.verify_gemfile_lock_has_updated.outputs.gemfiles }}
    steps:
      - uses: actions/checkout@v2

      - name: Verify If A Gem Has Been Added
        id: verify_gemfile_lock_has_updated
        uses: dorny/paths-filter@v2
        with:
            filters: |
              gemfiles:
                - './Gemfile'
                - './Gemfile.lock'
      - run: echo ${{ steps.verify_gemfile_lock_has_updated.outputs.gemfiles }}

  update_license:
    name: Generate License Information Report
    needs: [verify_conditions]
    if: needs.verify_conditions.outputs.status == 'true'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          
      - name: Checkout Project Directory
        run: cd /home/runner/work/aviaryplatform/aviaryplatform

      - name: Libs Installation
        run: sudo apt-get install libcurl4 libcurl4-openssl-dev

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install license_finder gem
        run: bundle install

      - name: Pull Current Branch
        run: git pull origin ${{ github.event.pull_request.base.ref }}

      - name: Run license_finder
        run: license_finder report --format=html --save=license_info.html

      - name: Add & Commit changes
        uses: EndBug/add-and-commit@v9.0.0
        with:
          author_name: Nouman Tayyab
          author_email: noumantayyab@gmail.com
          message: 'updated license infomation'
          add: './license_info.html'

  delete_branch:
      name: Delete Branch After Merge Is Complete
      if: always()
      needs: [verify_conditions, update_license]
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - run: echo ${{ github.event.pull_request.base.ref != 'main' && github.event.pull_request.base.ref != 'dev' }}
        - run: git push origin --delete ${{ github.event.pull_request.base.ref }}