name: Update License Information
on: 
  push:
    branches-ignore:
      - dev
      - main
    paths:
      - 'Gemfile'
      - 'Gemfile.lock'

jobs:
  update_license:
    name: Generate License Information Report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Checkout Project Directory
        run: cd /home/runner/work/aviary-public/aviary-public

      - name: Libs Installation
        run: sudo apt-get install libcurl4 libcurl4-openssl-dev
      - name: Pull Current Branch
        run: git pull origin ${{ github.event.pull_request.head.ref }}

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4

      - name: Install license_finder gem
        run: bundle install

      - name: Run license_finder
        run: license_finder report --format=html --save=license_info.html

      - name: Add & Commit changes
        uses: EndBug/add-and-commit@v9.0.0
        with:
          author_name: Nouman Tayyab
          author_email: noumantayyab@gmail.com
          message: 'updated license information'
          add: './license_info.html'